// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmPgbuD72LS96kSw6mv22Uvc7sR1-giHw',
    appId: '1:613500091552:web:4d530acfbc25dbe1b8ddc5',
    messagingSenderId: '613500091552',
    projectId: 'penyiram-tanaman-otomati-27e1a',
    authDomain: 'penyiram-tanaman-otomati-27e1a.firebaseapp.com',
    databaseURL: 'https://penyiram-tanaman-otomati-27e1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'penyiram-tanaman-otomati-27e1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWFP7yNKbbFpnHj_71G0NwzKX1Mf1j8PU',
    appId: '1:613500091552:android:c2cd4e67aa528586b8ddc5',
    messagingSenderId: '613500091552',
    projectId: 'penyiram-tanaman-otomati-27e1a',
    databaseURL: 'https://penyiram-tanaman-otomati-27e1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'penyiram-tanaman-otomati-27e1a.firebasestorage.app',
  );

}